#################### TODOLIST ####################
GET http://localhost:3000/todoList/todos HTTP/1.1
# Authorization: 'Bearer ' + this.props.token,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTU2NTU2LCJleHAiOjE2NDgxNjAxNTZ9.vaTeicMKfiZ0hW_h5t1Sr9lYGgC9lNgsIkHF67GIDkA
Content-Type: application/json

###
POST http://localhost:3000/todoList/todo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTU2NTU2LCJleHAiOjE2NDgxNjAxNTZ9.vaTeicMKfiZ0hW_h5t1Sr9lYGgC9lNgsIkHF67GIDkA
content-type: application/json

{
    "task": "Cook Dinner Tomorrow"
}

###
DELETE http://localhost:3000/todoList/todo/:todoId HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTUxNTMyLCJleHAiOjE2NDgxNTUxMzJ9.j6Hs7RKKJbieIuWmchGHezzQeldDwE1lg1Cg0QU4wlo

###
PUT http://localhost:3000/todoList/todo/:todoId HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTUxNTMyLCJleHAiOjE2NDgxNTUxMzJ9.j6Hs7RKKJbieIuWmchGHezzQeldDwE1lg1Cg0QU4wlo

# remove specific todo - enter a todoID
###
# DELETE http://localhost:3000/todoList/todo/623ccc55a8721e848598d82f HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTUxNTMyLCJleHAiOjE2NDgxNTUxMzJ9.j6Hs7RKKJbieIuWmchGHezzQeldDwE1lg1Cg0QU4wlo

#################### AUTH ####################
PUT http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test45@test.com",
    "name": "Tester",
    "password": "123456"
}

###
POST http://localhost:3000/auth/login
Authorization: 'Bearer ' + this.props.token,
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}

###
GET http://localhost:3000/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTU2NTU2LCJleHAiOjE2NDgxNjAxNTZ9.vaTeicMKfiZ0hW_h5t1Sr9lYGgC9lNgsIkHF67GIDkA

###
DELETE http://localhost:3000/auth/users/:userId

###
# DELETE http://localhost:3000/auth/users/623cc5280b526c0b74d871bf
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTU2NTU2LCJleHAiOjE2NDgxNjAxNTZ9.vaTeicMKfiZ0hW_h5t1Sr9lYGgC9lNgsIkHF67GIDkA
# content-type: application/json


#################### FAMILY ####################
POST http://localhost:3000/family/member HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTU2NTU2LCJleHAiOjE2NDgxNjAxNTZ9.vaTeicMKfiZ0hW_h5t1Sr9lYGgC9lNgsIkHF67GIDkA
content-type: application/json

{
    "name": "Prince Eric"
}

###
GET http://localhost:3000/family/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTU2NTU2LCJleHAiOjE2NDgxNjAxNTZ9.vaTeicMKfiZ0hW_h5t1Sr9lYGgC9lNgsIkHF67GIDkA

###
GET http://localhost:3000/family/member/:memberId

# Use for testing endpoints only - enter memberID
###
# GET http://localhost:3000/family/member/623be949ab3387d5d2c35b80 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTUxNTMyLCJleHAiOjE2NDgxNTUxMzJ9.j6Hs7RKKJbieIuWmchGHezzQeldDwE1lg1Cg0QU4wlo


###
DELETE http://localhost:3000/family/member/:memberId

###
# DELETE http://localhost:3000/family/member/623ce4ae8ed3eb6c8599109f
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoiNjIzYmNlODk1NzA1YmM3ZTEzM2E4ZmM2IiwiaWF0IjoxNjQ4MTU2NTU2LCJleHAiOjE2NDgxNjAxNTZ9.vaTeicMKfiZ0hW_h5t1Sr9lYGgC9lNgsIkHF67GIDkA
